### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Neralem** [eulerscheZahl/ParameterFiddler#6]
I get the following error message in the command window after it made a few rounds:

```
Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: 7
        at parameterfiddler.Runner.runBot(Runner.java:136)
        at parameterfiddler.Runner.mutateBot(Runner.java:219)
        at parameterfiddler.Runner.run(Runner.java:188)
        at java.lang.Thread.run(Unknown Source)
```

I started the fiddler with D:\CG BrutalTester\Seabed Security>java -jar ../uber-parameterfiddler-1.0.jar -gui
And this is the config file:

```
#Thu Jan 04 21:21:57 CET 2024
rounds=10
brutaltester=../cg-brutaltester.jar
players=2
threads=2
swap=true
delta=0.3
refereeCommand=java -jar fall-2023-fish.jar
```

This is my parameters.txt:
`public static int ScareCreatureEdgeDist { get; set; } = 2000;`

Parameter Changes Output Console:

```
Thu Jan 04 21:37:16 CET 2024: set parameter: public static int ScareCreatureEdgeDist { get; set; } = 2000;
Thu Jan 04 21:37:16 CET 2024: executing: [java, -jar, ../cg-brutaltester.jar, -r, "java -jar fall-2023-fish.jar", -p1, "D:\GoogleDrive\Eigene Programme\CSharp\CodingGame\FallChallenge2023\bin\Debug\net6.0\FallChallenge2023.exe mutatedParameters.txt", -p2, "D:\GoogleDrive\Eigene Programme\CSharp\CodingGame\FallChallenge2023\bin\Debug\net6.0\FallChallenge2023.exe parameters.txt", -t2, -n100, -s]
```

Brutaltester Output Console:

```
21:37:16,941 INFO  [com.magusgeek.brutaltester.Main] Referee command line: java -jar fall-2023-fish.jar
21:37:16,942 INFO  [com.magusgeek.brutaltester.Main] Player 1 command line: D:\GoogleDrive\Eigene Programme\CSharp\CodingGame\FallChallenge2023\bin\Debug\net6.0\FallChallenge2023.exe mutatedParameters.txt
21:37:16,942 INFO  [com.magusgeek.brutaltester.Main] Player 2 command line: D:\GoogleDrive\Eigene Programme\CSharp\CodingGame\FallChallenge2023\bin\Debug\net6.0\FallChallenge2023.exe parameters.txt
21:37:16,942 INFO  [com.magusgeek.brutaltester.Main] Number of games to play: 100
21:37:16,942 INFO  [com.magusgeek.brutaltester.Main] Number of threads to spawn: 2
21:37:17,791 INFO  [com.magusgeek.brutaltester.GameThread] End of game 1	 0,00% 0,00%
21:37:17,805 INFO  [com.magusgeek.brutaltester.GameThread] End of game 2	 0,00% 0,00%
21:37:18,461 INFO  [com.magusgeek.brutaltester.GameThread] End of game 4	 0,00% 0,00%
21:37:18,461 INFO  [com.magusgeek.brutaltester.GameThread] End of game 3	 0,00% 0,00%
21:37:19,328 INFO  [com.magusgeek.brutaltester.GameThread] End of game 5	 0,00% 0,00%
21:37:19,332 INFO  [com.magusgeek.brutaltester.GameThread] End of game 6	 0,00% 0,00%
21:37:20,191 INFO  [com.magusgeek.brutaltester.GameThread] End of game 8	 0,00% 0,00%
21:37:20,192 INFO  [com.magusgeek.brutaltester.GameThread] End of game 7	 0,00% 0,00%
21:37:20,994 INFO  [com.magusgeek.brutaltester.GameThread] End of game 10	 0,00% 0,00%
21:37:20,996 INFO  [com.magusgeek.brutaltester.GameThread] End of game 9	 0,00% 0,00%
21:37:21,659 INFO  [com.magusgeek.brutaltester.GameThread] End of game 11	 0,00% 0,00%
21:37:21,659 INFO  [com.magusgeek.brutaltester.GameThread] End of game 12	 0,00% 0,00%
21:37:22,479 INFO  [com.magusgeek.brutaltester.GameThread] End of game 13	 0,00% 0,00%
21:37:22,479 INFO  [com.magusgeek.brutaltester.GameThread] End of game 14	 0,00% 0,00%
21:37:23,461 INFO  [com.magusgeek.brutaltester.GameThread] End of game 15	 0,00% 0,00%
21:37:23,462 INFO  [com.magusgeek.brutaltester.GameThread] End of game 16	 0,00% 0,00%
21:37:24,261 INFO  [com.magusgeek.brutaltester.GameThread] End of game 17	 0,00% 0,00%
21:37:24,263 INFO  [com.magusgeek.brutaltester.GameThread] End of game 18	 0,00% 0,00%
21:37:25,075 INFO  [com.magusgeek.brutaltester.GameThread] End of game 19	 0,00% 0,00%
21:37:25,081 INFO  [com.magusgeek.brutaltester.GameThread] End of game 20	 0,00% 0,00%
21:37:25,817 INFO  [com.magusgeek.brutaltester.GameThread] End of game 21	 0,00% 0,00%
21:37:25,821 INFO  [com.magusgeek.brutaltester.GameThread] End of game 22	 0,00% 0,00%
21:37:26,522 INFO  [com.magusgeek.brutaltester.GameThread] End of game 24	 0,00% 0,00%
21:37:26,522 INFO  [com.magusgeek.brutaltester.GameThread] End of game 23	 0,00% 0,00%
21:37:27,382 INFO  [com.magusgeek.brutaltester.GameThread] End of game 25	 4,00% 3,85%
```

**Comment by Neralem** [comment]
The Error is not deterministic in terms of the amount of rounds that it will work.
Brutaltester itself works very well.

**Comment by eulerscheZahl** [comment]
Hello,
it's been a while that I wrote this and there are probably better ways out there (e.g. Optuna).

The ParamFiddler is built with an older version of brutaltester in mind, that would output a ranking list after each individual match. E.g. "1 0" (0-indexed) would mean that player 2 won and player 1 got 2nd, "01" (without space) is a draw. Times have changed and I should probably just archive this project.

**Comment by Neralem** [comment]
Oh okay. Thanks! I'll check out the alternative you suggested. Happy new year :)
